name: Run Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker build . -t faiss_search:latest

      - name: Run Pytest
        run: docker run -i -v $PWD:/srv -w/srv faiss_search pytest tests/ --junit-xml=.test_report.xml

      - name: Generate PyTest report
        uses: test-summary/action@v2
        with:
          paths: .test_report.xml
          show: fail
        if: always()